"""hhd

Revision ID: c0fe0f64cc0c
Revises: 9363147bdf00
Create Date: 2025-01-11 16:50:44.410859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0fe0f64cc0c'
down_revision = '9363147bdf00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('is_boarding')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_boarding', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
